### ISSUE TITLE
结果问题？

### ISSUE THREAD

**Issue by duke-feng** [Daikenan/ASRCF#10]
请问一下，我用您公布的代码复现（参数都是您之前设置好的）出来的在OTB100上只有0.90，可是给的结果有0.922，想问一下是什么原因？

**Comment by Daikenan** [comment]
是复现还是直接用原始版本测OTB100？我提交前在两个不同机器上测了一遍，都是92，这份代码是没有随机的。

**Comment by Daikenan** [comment]
还有测OTB100要注意一下起始帧和结束帧，比如David是从300帧开始的，Diving是215帧结束。

**Comment by duke-feng** [comment]
用您公布的代码跑的，OTB100起始帧，结束帧也是一样的，哦我用的是CPU跑的，有可能是这个的问题吗？谢谢了！

**Comment by Daikenan** [comment]
CPU和GPU的结果是有出入的，可能是采样函数的问题。

**Comment by sysu-shey** [comment]
您好，我在单块1080Ti 环境下测试（未改动源代码），结果分别是0.912和0.687，并没有达到论文的结果，请问还有可能是什么原因呀 @Daikenan 谢谢了！
