### ISSUE TITLE
有关BACF系列的推导

### ISSUE THREAD

**Issue by soldatjiang** [Daikenan/ASRCF#11]
看了很多和BACF有关的论文，推导的结果和code都不一致，我尝试了一下，如果ASRCF论文中(5)式第一项前面的系数改成1/(2T)，结果就和code一致了，是大部分论文的推导过程都错了吗？

**Comment by Daikenan** [comment]
这个问题的产生是论文里傅里叶变化和matlab的实现不一致，论文里用的离散的傅里叶变换是数学上的定义`a^hat=sqrt(T)Fa`，而matlab的fft函数是:`fft(a)=Fa`.所以在matlab实现的时候涉及`fft(a)*fft(a)'`类似的操作时前面要乘以1/T.
