### ISSUE TITLE
您好，请问一下，我想要使用prevggmfeature来做测试，我应该怎么去修改目前代码里面的参数配置信息呢？谢谢您！

### ISSUE THREAD

**Issue by shuyuandeqipa** [Daikenan/ASRCF#12]

**Comment by Daikenan** [comment]
你可以直接修改extract_feature.m的输出，可以换成其他的网络比如resnet或者是你自己训网络，然后你需要在ASRCF_optimized.m里做适当的修改，比如特征cat那块。
