### ISSUE TITLE
请问MATLAB运行ASRCF代码出错，该怎么解决？

### ISSUE THREAD

**Issue by zangshouyu111** [Daikenan/ASRCF#15]
警告: 名称不存在或不是目录: C:\Users\user\Desktop\ASRCF-master\external_libs\matconvnet\matlab\mex 
> In path (line 109)
  In addpath (line 96)
  In vl_setupnn (line 13)
  In setup_path (line 15)
  In ASRCF_Demo (line 6) 
警告: MatConvNet is not compiled. Consider running `vl_compilenn`. 
> In vl_setupnn (line 24)
  In setup_path (line 15)
  In ASRCF_Demo (line 6) 
尝试将 SCRIPT vl_nnconv 作为函数执行:
C:\Users\user\Desktop\ASRCF-master\external_libs\matconvnet\matlab\vl_nnconv.m

出错 vl_simplenn (line 300)
      res(i+1).x = vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, ...

出错 get_vggfeatures (line 32)
res = vl_simplenn(vgg16net,img);

出错 extract_features (line 3)
   x_vgg16= get_vggfeatures(patch,use_sz,23);

出错 ASRCF_optimized (line 262)
         x=extract_features(pixels,use_sz,features,global_feat_params,frame,ifcompress,pe);

出错 run_ASRCF (line 70)
results = ASRCF_optimized(params);

出错 ASRCF_Demo (line 17)
results = run_ASRCF(seq, video_path);
 
>>

**Comment by Daikenan** [comment]
matconvnet没有成功编译，最好用Ubuntu系统，install.m是在Ubuntu系统下测试的。如果要用window10可以参考https://github.com/Daikenan/ASRCF/issues/5#issuecomment-523272805

**Comment by zangshouyu111** [comment]
您好，我是最近刚了解相关滤波，然后我也知道你们团队在这块领域特别厉害。我想问一下，你们团队的代码都要在这个环境下运行吗？

**Comment by zangshouyu111** [comment]
您好，我是最近刚了解相关滤波，然后我也知道你们团队在这块领域特别厉害。我想问一下，你们团队的代码都要在这个环境下运行吗？

**Comment by zangshouyu111** [comment]
您好，我是最近刚了解相关滤波，然后我也知道你们团队在这块领域特别厉害。我想问一下，你们团队的代码都要在这个环境下运行吗？

**Comment by zangshouyu111** [comment]
您好，我是最近刚了解相关滤波，然后我也知道你们团队在这块领域特别厉害。我想问一下，你们团队的代码都要在这个环境下运行吗？
