### ISSUE TITLE
在VOT2016上的结果问题

### ISSUE THREAD

**Issue by yizzzhang** [Daikenan/ASRCF#17]
您好，请问一下，我用您公布的代码（参数不变）在VOT2016上测试，可是结果有0.2864，文章中给出的结果是0.391，想问一下是什么原因？我是在Windows系统上复现，是因为系统不同还是参数需要调的原因？

**Comment by HEXIN3498** [comment]
您好，我想问一下，ASRCF代码运行之前需要install,我怎么做才能用他来跑OTB100

**Comment by yizzzhang** [comment]
> 您好，我想问一下，ASRCF代码运行之前需要install,我怎么做才能用他来跑OTB100

您好，我是在Windows系统运行的，不太清楚您指的install是什么内容，如果要跑OTB的话，最好先单独运行demo代码看能否跑通，如果运行成功的话写好接口函数就可以在OTB上运行了。

**Comment by sysu-shey** [comment]
请问可以分享一下在VOT上运行的接口函数么

**Comment by sysu-shey** [comment]
您好，请问一下，我用您公布的代码（参数不变）在VOT2016上测试，可是结果有0.2696，文章中给出的结果是0.391，想问一下是什么原因？我是在Windows系统上复现，是因为系统不同还是参数需要调的原因？ @Daikenan

**Comment by Daikenan** [comment]
原因可能是多方面的，我没有在windows上测试过，并不清楚会有多大差异，另外VOT都是单独一套参数，我之后会提供VOT的接口函数。
