### ISSUE TITLE
在OTB数据集上的测试结果与论文不符问题

### ISSUE THREAD

**Issue by sysu-shey** [Daikenan/ASRCF#18]
您好，我在单块1080Ti 环境下测试（未改动源代码），结果分别是0.912和0.687，并没有达到论文的结果，请问还有可能是什么原因呀 @Daikenan 谢谢了！

**Comment by Daikenan** [comment]
这个问题之前有不少人反映过，大部分原因都是由于OTB数据读取的问题，起始帧和结束帧，如果过程正确，最终presion大约是0.921-0.922，AUC大约是0.692-0.693，我之后会提供一个测试OTB的接口。
