### ISSUE TITLE
请问可以公布VOT2016的结果么？

### ISSUE THREAD

**Issue by 0005f** [Daikenan/ASRCF#19]
您好~请问 您可以放出您VOT2016数据库的运行结果么？看到您整理出的OTB和其他数据集的，请问可以放一下论文中VOT2016数据集的结果么

**Comment by 0005f** [comment]
您好 或者您可以提供一下VOT2016数据集的参数和接口函数吗？

**Comment by Daikenan** [comment]
结果文件已上传，接口之后提供
